version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_ENV_URL}
      DB_USERNAME: ${APP_USERNAME}
      DB_PASSWORD: ${APP_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
